services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8000"

    environment:
      ENVIRONMENT: development
    volumes:
      - ./backend/src:/src/backend/src 

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  