name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    name: Ruff (Lint & Format)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: backend/poetry.lock

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Check formatting
        run: poetry run ruff format --check .

      - name: Lint
        run: poetry run ruff check .

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: backend/poetry.lock

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest